//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsaWSCalc.WS_EXT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Varios", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Varios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MulField;
        
        private int SumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Mul {
            get {
                return this.MulField;
            }
            set {
                if ((this.MulField.Equals(value) != true)) {
                    this.MulField = value;
                    this.RaisePropertyChanged("Mul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_EXT.CalcSuperSoap")]
    public interface CalcSuperSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        UsaWSCalc.WS_EXT.HelloWorldResponse HelloWorld(UsaWSCalc.WS_EXT.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(UsaWSCalc.WS_EXT.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        UsaWSCalc.WS_EXT.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SomaPlus", ReplyAction="*")]
        int SomaPlus(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SomaPlus", ReplyAction="*")]
        System.IAsyncResult BeginSomaPlus(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSomaPlus(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name SomaMulResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SomaMul", ReplyAction="*")]
        UsaWSCalc.WS_EXT.SomaMulResponse SomaMul(UsaWSCalc.WS_EXT.SomaMulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SomaMul", ReplyAction="*")]
        System.IAsyncResult BeginSomaMul(UsaWSCalc.WS_EXT.SomaMulRequest request, System.AsyncCallback callback, object asyncState);
        
        UsaWSCalc.WS_EXT.SomaMulResponse EndSomaMul(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public UsaWSCalc.WS_EXT.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(UsaWSCalc.WS_EXT.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public UsaWSCalc.WS_EXT.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(UsaWSCalc.WS_EXT.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomaMulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SomaMul", Namespace="http://tempuri.org/", Order=0)]
        public UsaWSCalc.WS_EXT.SomaMulRequestBody Body;
        
        public SomaMulRequest() {
        }
        
        public SomaMulRequest(UsaWSCalc.WS_EXT.SomaMulRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SomaMulRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int y;
        
        public SomaMulRequestBody() {
        }
        
        public SomaMulRequestBody(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomaMulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SomaMulResponse", Namespace="http://tempuri.org/", Order=0)]
        public UsaWSCalc.WS_EXT.SomaMulResponseBody Body;
        
        public SomaMulResponse() {
        }
        
        public SomaMulResponse(UsaWSCalc.WS_EXT.SomaMulResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SomaMulResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UsaWSCalc.WS_EXT.Varios SomaMulResult;
        
        public SomaMulResponseBody() {
        }
        
        public SomaMulResponseBody(UsaWSCalc.WS_EXT.Varios SomaMulResult) {
            this.SomaMulResult = SomaMulResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSuperSoapChannel : UsaWSCalc.WS_EXT.CalcSuperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SomaPlusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SomaPlusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SomaMulCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SomaMulCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UsaWSCalc.WS_EXT.Varios Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UsaWSCalc.WS_EXT.Varios)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSuperSoapClient : System.ServiceModel.ClientBase<UsaWSCalc.WS_EXT.CalcSuperSoap>, UsaWSCalc.WS_EXT.CalcSuperSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginSomaPlusDelegate;
        
        private EndOperationDelegate onEndSomaPlusDelegate;
        
        private System.Threading.SendOrPostCallback onSomaPlusCompletedDelegate;
        
        private BeginOperationDelegate onBeginSomaMulDelegate;
        
        private EndOperationDelegate onEndSomaMulDelegate;
        
        private System.Threading.SendOrPostCallback onSomaMulCompletedDelegate;
        
        public CalcSuperSoapClient() {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSuperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<SomaPlusCompletedEventArgs> SomaPlusCompleted;
        
        public event System.EventHandler<SomaMulCompletedEventArgs> SomaMulCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsaWSCalc.WS_EXT.HelloWorldResponse UsaWSCalc.WS_EXT.CalcSuperSoap.HelloWorld(UsaWSCalc.WS_EXT.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            UsaWSCalc.WS_EXT.HelloWorldRequest inValue = new UsaWSCalc.WS_EXT.HelloWorldRequest();
            inValue.Body = new UsaWSCalc.WS_EXT.HelloWorldRequestBody();
            UsaWSCalc.WS_EXT.HelloWorldResponse retVal = ((UsaWSCalc.WS_EXT.CalcSuperSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UsaWSCalc.WS_EXT.CalcSuperSoap.BeginHelloWorld(UsaWSCalc.WS_EXT.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            UsaWSCalc.WS_EXT.HelloWorldRequest inValue = new UsaWSCalc.WS_EXT.HelloWorldRequest();
            inValue.Body = new UsaWSCalc.WS_EXT.HelloWorldRequestBody();
            return ((UsaWSCalc.WS_EXT.CalcSuperSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsaWSCalc.WS_EXT.HelloWorldResponse UsaWSCalc.WS_EXT.CalcSuperSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorld(System.IAsyncResult result) {
            UsaWSCalc.WS_EXT.HelloWorldResponse retVal = ((UsaWSCalc.WS_EXT.CalcSuperSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        public int SomaPlus(int x, int y) {
            return base.Channel.SomaPlus(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSomaPlus(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSomaPlus(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSomaPlus(System.IAsyncResult result) {
            return base.Channel.EndSomaPlus(result);
        }
        
        private System.IAsyncResult OnBeginSomaPlus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSomaPlus(x, y, callback, asyncState);
        }
        
        private object[] OnEndSomaPlus(System.IAsyncResult result) {
            int retVal = this.EndSomaPlus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSomaPlusCompleted(object state) {
            if ((this.SomaPlusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SomaPlusCompleted(this, new SomaPlusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SomaPlusAsync(int x, int y) {
            this.SomaPlusAsync(x, y, null);
        }
        
        public void SomaPlusAsync(int x, int y, object userState) {
            if ((this.onBeginSomaPlusDelegate == null)) {
                this.onBeginSomaPlusDelegate = new BeginOperationDelegate(this.OnBeginSomaPlus);
            }
            if ((this.onEndSomaPlusDelegate == null)) {
                this.onEndSomaPlusDelegate = new EndOperationDelegate(this.OnEndSomaPlus);
            }
            if ((this.onSomaPlusCompletedDelegate == null)) {
                this.onSomaPlusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSomaPlusCompleted);
            }
            base.InvokeAsync(this.onBeginSomaPlusDelegate, new object[] {
                        x,
                        y}, this.onEndSomaPlusDelegate, this.onSomaPlusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsaWSCalc.WS_EXT.SomaMulResponse UsaWSCalc.WS_EXT.CalcSuperSoap.SomaMul(UsaWSCalc.WS_EXT.SomaMulRequest request) {
            return base.Channel.SomaMul(request);
        }
        
        public UsaWSCalc.WS_EXT.Varios SomaMul(int x, int y) {
            UsaWSCalc.WS_EXT.SomaMulRequest inValue = new UsaWSCalc.WS_EXT.SomaMulRequest();
            inValue.Body = new UsaWSCalc.WS_EXT.SomaMulRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            UsaWSCalc.WS_EXT.SomaMulResponse retVal = ((UsaWSCalc.WS_EXT.CalcSuperSoap)(this)).SomaMul(inValue);
            return retVal.Body.SomaMulResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UsaWSCalc.WS_EXT.CalcSuperSoap.BeginSomaMul(UsaWSCalc.WS_EXT.SomaMulRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSomaMul(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSomaMul(int x, int y, System.AsyncCallback callback, object asyncState) {
            UsaWSCalc.WS_EXT.SomaMulRequest inValue = new UsaWSCalc.WS_EXT.SomaMulRequest();
            inValue.Body = new UsaWSCalc.WS_EXT.SomaMulRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((UsaWSCalc.WS_EXT.CalcSuperSoap)(this)).BeginSomaMul(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsaWSCalc.WS_EXT.SomaMulResponse UsaWSCalc.WS_EXT.CalcSuperSoap.EndSomaMul(System.IAsyncResult result) {
            return base.Channel.EndSomaMul(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public UsaWSCalc.WS_EXT.Varios EndSomaMul(System.IAsyncResult result) {
            UsaWSCalc.WS_EXT.SomaMulResponse retVal = ((UsaWSCalc.WS_EXT.CalcSuperSoap)(this)).EndSomaMul(result);
            return retVal.Body.SomaMulResult;
        }
        
        private System.IAsyncResult OnBeginSomaMul(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSomaMul(x, y, callback, asyncState);
        }
        
        private object[] OnEndSomaMul(System.IAsyncResult result) {
            UsaWSCalc.WS_EXT.Varios retVal = this.EndSomaMul(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSomaMulCompleted(object state) {
            if ((this.SomaMulCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SomaMulCompleted(this, new SomaMulCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SomaMulAsync(int x, int y) {
            this.SomaMulAsync(x, y, null);
        }
        
        public void SomaMulAsync(int x, int y, object userState) {
            if ((this.onBeginSomaMulDelegate == null)) {
                this.onBeginSomaMulDelegate = new BeginOperationDelegate(this.OnBeginSomaMul);
            }
            if ((this.onEndSomaMulDelegate == null)) {
                this.onEndSomaMulDelegate = new EndOperationDelegate(this.OnEndSomaMul);
            }
            if ((this.onSomaMulCompletedDelegate == null)) {
                this.onSomaMulCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSomaMulCompleted);
            }
            base.InvokeAsync(this.onBeginSomaMulDelegate, new object[] {
                        x,
                        y}, this.onEndSomaMulDelegate, this.onSomaMulCompletedDelegate, userState);
        }
    }
}
