//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsaCalcWS.WS_EXT_2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VariasCoisas", Namespace="http://xxx.yyy.pt/")]
    [System.SerializableAttribute()]
    public partial class VariasCoisas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SumField;
        
        private int SubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Sub {
            get {
                return this.SubField;
            }
            set {
                if ((this.SubField.Equals(value) != true)) {
                    this.SubField = value;
                    this.RaisePropertyChanged("Sub");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xxx.yyy.pt/", ConfigurationName="WS_EXT_2.CalcSuperSoap")]
    public interface CalcSuperSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/Soma", ReplyAction="*")]
        int Soma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://xxx.yyy.pt/Soma", ReplyAction="*")]
        System.IAsyncResult BeginSoma(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSoma(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://xxx.yyy.pt/Sub", ReplyAction="*")]
        System.IAsyncResult BeginSub(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndSub(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name SumESubResult from namespace http://xxx.yyy.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/SumESub", ReplyAction="*")]
        UsaCalcWS.WS_EXT_2.SumESubResponse SumESub(UsaCalcWS.WS_EXT_2.SumESubRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://xxx.yyy.pt/SumESub", ReplyAction="*")]
        System.IAsyncResult BeginSumESub(UsaCalcWS.WS_EXT_2.SumESubRequest request, System.AsyncCallback callback, object asyncState);
        
        UsaCalcWS.WS_EXT_2.SumESubResponse EndSumESub(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumESubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumESub", Namespace="http://xxx.yyy.pt/", Order=0)]
        public UsaCalcWS.WS_EXT_2.SumESubRequestBody Body;
        
        public SumESubRequest() {
        }
        
        public SumESubRequest(UsaCalcWS.WS_EXT_2.SumESubRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xxx.yyy.pt/")]
    public partial class SumESubRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int y;
        
        public SumESubRequestBody() {
        }
        
        public SumESubRequestBody(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumESubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumESubResponse", Namespace="http://xxx.yyy.pt/", Order=0)]
        public UsaCalcWS.WS_EXT_2.SumESubResponseBody Body;
        
        public SumESubResponse() {
        }
        
        public SumESubResponse(UsaCalcWS.WS_EXT_2.SumESubResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xxx.yyy.pt/")]
    public partial class SumESubResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UsaCalcWS.WS_EXT_2.VariasCoisas SumESubResult;
        
        public SumESubResponseBody() {
        }
        
        public SumESubResponseBody(UsaCalcWS.WS_EXT_2.VariasCoisas SumESubResult) {
            this.SumESubResult = SumESubResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSuperSoapChannel : UsaCalcWS.WS_EXT_2.CalcSuperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SumESubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SumESubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UsaCalcWS.WS_EXT_2.VariasCoisas Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UsaCalcWS.WS_EXT_2.VariasCoisas)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSuperSoapClient : System.ServiceModel.ClientBase<UsaCalcWS.WS_EXT_2.CalcSuperSoap>, UsaCalcWS.WS_EXT_2.CalcSuperSoap {
        
        private BeginOperationDelegate onBeginSomaDelegate;
        
        private EndOperationDelegate onEndSomaDelegate;
        
        private System.Threading.SendOrPostCallback onSomaCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubDelegate;
        
        private EndOperationDelegate onEndSubDelegate;
        
        private System.Threading.SendOrPostCallback onSubCompletedDelegate;
        
        private BeginOperationDelegate onBeginSumESubDelegate;
        
        private EndOperationDelegate onEndSumESubDelegate;
        
        private System.Threading.SendOrPostCallback onSumESubCompletedDelegate;
        
        public CalcSuperSoapClient() {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSuperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SomaCompletedEventArgs> SomaCompleted;
        
        public event System.EventHandler<SubCompletedEventArgs> SubCompleted;
        
        public event System.EventHandler<SumESubCompletedEventArgs> SumESubCompleted;
        
        public int Soma(int x, int y) {
            return base.Channel.Soma(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSoma(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSoma(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSoma(System.IAsyncResult result) {
            return base.Channel.EndSoma(result);
        }
        
        private System.IAsyncResult OnBeginSoma(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSoma(x, y, callback, asyncState);
        }
        
        private object[] OnEndSoma(System.IAsyncResult result) {
            int retVal = this.EndSoma(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSomaCompleted(object state) {
            if ((this.SomaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SomaCompleted(this, new SomaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SomaAsync(int x, int y) {
            this.SomaAsync(x, y, null);
        }
        
        public void SomaAsync(int x, int y, object userState) {
            if ((this.onBeginSomaDelegate == null)) {
                this.onBeginSomaDelegate = new BeginOperationDelegate(this.OnBeginSoma);
            }
            if ((this.onEndSomaDelegate == null)) {
                this.onEndSomaDelegate = new EndOperationDelegate(this.OnEndSoma);
            }
            if ((this.onSomaCompletedDelegate == null)) {
                this.onSomaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSomaCompleted);
            }
            base.InvokeAsync(this.onBeginSomaDelegate, new object[] {
                        x,
                        y}, this.onEndSomaDelegate, this.onSomaCompletedDelegate, userState);
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSub(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSub(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndSub(System.IAsyncResult result) {
            return base.Channel.EndSub(result);
        }
        
        private System.IAsyncResult OnBeginSub(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSub(x, y, callback, asyncState);
        }
        
        private object[] OnEndSub(System.IAsyncResult result) {
            int retVal = this.EndSub(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubCompleted(object state) {
            if ((this.SubCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubCompleted(this, new SubCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubAsync(int x, int y) {
            this.SubAsync(x, y, null);
        }
        
        public void SubAsync(int x, int y, object userState) {
            if ((this.onBeginSubDelegate == null)) {
                this.onBeginSubDelegate = new BeginOperationDelegate(this.OnBeginSub);
            }
            if ((this.onEndSubDelegate == null)) {
                this.onEndSubDelegate = new EndOperationDelegate(this.OnEndSub);
            }
            if ((this.onSubCompletedDelegate == null)) {
                this.onSubCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubCompleted);
            }
            base.InvokeAsync(this.onBeginSubDelegate, new object[] {
                        x,
                        y}, this.onEndSubDelegate, this.onSubCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsaCalcWS.WS_EXT_2.SumESubResponse UsaCalcWS.WS_EXT_2.CalcSuperSoap.SumESub(UsaCalcWS.WS_EXT_2.SumESubRequest request) {
            return base.Channel.SumESub(request);
        }
        
        public UsaCalcWS.WS_EXT_2.VariasCoisas SumESub(int x, int y) {
            UsaCalcWS.WS_EXT_2.SumESubRequest inValue = new UsaCalcWS.WS_EXT_2.SumESubRequest();
            inValue.Body = new UsaCalcWS.WS_EXT_2.SumESubRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            UsaCalcWS.WS_EXT_2.SumESubResponse retVal = ((UsaCalcWS.WS_EXT_2.CalcSuperSoap)(this)).SumESub(inValue);
            return retVal.Body.SumESubResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UsaCalcWS.WS_EXT_2.CalcSuperSoap.BeginSumESub(UsaCalcWS.WS_EXT_2.SumESubRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSumESub(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSumESub(int x, int y, System.AsyncCallback callback, object asyncState) {
            UsaCalcWS.WS_EXT_2.SumESubRequest inValue = new UsaCalcWS.WS_EXT_2.SumESubRequest();
            inValue.Body = new UsaCalcWS.WS_EXT_2.SumESubRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((UsaCalcWS.WS_EXT_2.CalcSuperSoap)(this)).BeginSumESub(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsaCalcWS.WS_EXT_2.SumESubResponse UsaCalcWS.WS_EXT_2.CalcSuperSoap.EndSumESub(System.IAsyncResult result) {
            return base.Channel.EndSumESub(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public UsaCalcWS.WS_EXT_2.VariasCoisas EndSumESub(System.IAsyncResult result) {
            UsaCalcWS.WS_EXT_2.SumESubResponse retVal = ((UsaCalcWS.WS_EXT_2.CalcSuperSoap)(this)).EndSumESub(result);
            return retVal.Body.SumESubResult;
        }
        
        private System.IAsyncResult OnBeginSumESub(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginSumESub(x, y, callback, asyncState);
        }
        
        private object[] OnEndSumESub(System.IAsyncResult result) {
            UsaCalcWS.WS_EXT_2.VariasCoisas retVal = this.EndSumESub(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSumESubCompleted(object state) {
            if ((this.SumESubCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SumESubCompleted(this, new SumESubCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SumESubAsync(int x, int y) {
            this.SumESubAsync(x, y, null);
        }
        
        public void SumESubAsync(int x, int y, object userState) {
            if ((this.onBeginSumESubDelegate == null)) {
                this.onBeginSumESubDelegate = new BeginOperationDelegate(this.OnBeginSumESub);
            }
            if ((this.onEndSumESubDelegate == null)) {
                this.onEndSumESubDelegate = new EndOperationDelegate(this.OnEndSumESub);
            }
            if ((this.onSumESubCompletedDelegate == null)) {
                this.onSumESubCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSumESubCompleted);
            }
            base.InvokeAsync(this.onBeginSumESubDelegate, new object[] {
                        x,
                        y}, this.onEndSumESubDelegate, this.onSumESubCompletedDelegate, userState);
        }
    }
}
