//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsaWSCalc.WS_EXT_2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VariasCoisas", Namespace="http://xxx.yyy.pt/")]
    [System.SerializableAttribute()]
    public partial class VariasCoisas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SumField;
        
        private int SubField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Sub {
            get {
                return this.SubField;
            }
            set {
                if ((this.SubField.Equals(value) != true)) {
                    this.SubField = value;
                    this.RaisePropertyChanged("Sub");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xxx.yyy.pt/", ConfigurationName="WS_EXT_2.CalcSuperSoap")]
    public interface CalcSuperSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/Soma", ReplyAction="*")]
        int Soma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/Soma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SomaAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name SumESubResult from namespace http://xxx.yyy.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/SumESub", ReplyAction="*")]
        UsaWSCalc.WS_EXT_2.SumESubResponse SumESub(UsaWSCalc.WS_EXT_2.SumESubRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.yyy.pt/SumESub", ReplyAction="*")]
        System.Threading.Tasks.Task<UsaWSCalc.WS_EXT_2.SumESubResponse> SumESubAsync(UsaWSCalc.WS_EXT_2.SumESubRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumESubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumESub", Namespace="http://xxx.yyy.pt/", Order=0)]
        public UsaWSCalc.WS_EXT_2.SumESubRequestBody Body;
        
        public SumESubRequest() {
        }
        
        public SumESubRequest(UsaWSCalc.WS_EXT_2.SumESubRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xxx.yyy.pt/")]
    public partial class SumESubRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int y;
        
        public SumESubRequestBody() {
        }
        
        public SumESubRequestBody(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumESubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumESubResponse", Namespace="http://xxx.yyy.pt/", Order=0)]
        public UsaWSCalc.WS_EXT_2.SumESubResponseBody Body;
        
        public SumESubResponse() {
        }
        
        public SumESubResponse(UsaWSCalc.WS_EXT_2.SumESubResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xxx.yyy.pt/")]
    public partial class SumESubResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UsaWSCalc.WS_EXT_2.VariasCoisas SumESubResult;
        
        public SumESubResponseBody() {
        }
        
        public SumESubResponseBody(UsaWSCalc.WS_EXT_2.VariasCoisas SumESubResult) {
            this.SumESubResult = SumESubResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSuperSoapChannel : UsaWSCalc.WS_EXT_2.CalcSuperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSuperSoapClient : System.ServiceModel.ClientBase<UsaWSCalc.WS_EXT_2.CalcSuperSoap>, UsaWSCalc.WS_EXT_2.CalcSuperSoap {
        
        public CalcSuperSoapClient() {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSuperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSuperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Soma(int x, int y) {
            return base.Channel.Soma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SomaAsync(int x, int y) {
            return base.Channel.SomaAsync(x, y);
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int x, int y) {
            return base.Channel.SubAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsaWSCalc.WS_EXT_2.SumESubResponse UsaWSCalc.WS_EXT_2.CalcSuperSoap.SumESub(UsaWSCalc.WS_EXT_2.SumESubRequest request) {
            return base.Channel.SumESub(request);
        }
        
        public UsaWSCalc.WS_EXT_2.VariasCoisas SumESub(int x, int y) {
            UsaWSCalc.WS_EXT_2.SumESubRequest inValue = new UsaWSCalc.WS_EXT_2.SumESubRequest();
            inValue.Body = new UsaWSCalc.WS_EXT_2.SumESubRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            UsaWSCalc.WS_EXT_2.SumESubResponse retVal = ((UsaWSCalc.WS_EXT_2.CalcSuperSoap)(this)).SumESub(inValue);
            return retVal.Body.SumESubResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsaWSCalc.WS_EXT_2.SumESubResponse> UsaWSCalc.WS_EXT_2.CalcSuperSoap.SumESubAsync(UsaWSCalc.WS_EXT_2.SumESubRequest request) {
            return base.Channel.SumESubAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsaWSCalc.WS_EXT_2.SumESubResponse> SumESubAsync(int x, int y) {
            UsaWSCalc.WS_EXT_2.SumESubRequest inValue = new UsaWSCalc.WS_EXT_2.SumESubRequest();
            inValue.Body = new UsaWSCalc.WS_EXT_2.SumESubRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((UsaWSCalc.WS_EXT_2.CalcSuperSoap)(this)).SumESubAsync(inValue);
        }
    }
}
